import localFont from "next/font/local";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { assets } from "@/asstes/assets";
config.autoAddCss = false

const outfit = localFont({
  src: "./fonts/MomoTrustDisplay-Regular.ttf", 
  variable: "--font-momo-trust",
  weight: "400",
  style: "normal",
})



export const metadata = {
  title: "Mrinal Devnath's - AARC Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" rel="icon" className="scroll-smooth ">
      <link href={assets.helog} />
      <body id="dark-theme"
        className={`${outfit.className} ${outfit.className} antialiased leading-8 overflow-x-hidden `}
      >
        {children}
      </body>
    </html>
  );
}
